#pragma once

#include <string>
#include <chrono>
#include <cmath>
#include <memory>
#include <queue>
#include <string>
#include <type_traits>
#include <utility>
#include <sstream>
#include <vector>

#if __cplusplus < 201703L
// Fallback for toolchains/IntelliSense not using C++17.
namespace std {
template <class From, class To>
constexpr bool is_convertible_v = std::is_convertible<From, To>::value;
}  // namespace std
#endif

#include "hardware_interface/types/hardware_interface_type_values.hpp"
#include "rclcpp/logging.hpp"
#include "tf2/LinearMath/Quaternion.h"
#include "controller_interface/controller_interface.hpp"
#include "geometry_msgs/msg/twist.hpp"
#include "geometry_msgs/msg/twist_stamped.hpp"
#include "hardware_interface/handle.hpp"
#include "nav_msgs/msg/odometry.hpp"
#include "rclcpp/rclcpp.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_box.hpp"
#include "realtime_tools/realtime_publisher.hpp"
#include "tf2_msgs/msg/tf_message.hpp"
#include "lifecycle_msgs/msg/state.hpp"

// auto-generated by generate_parameter_library
#include "fr3_husky_controller/test_husky_controller_parameters.hpp"

#include "dyros_robot_controller/mobile/robot_data.h"
#include "dyros_robot_controller/mobile/robot_controller.h"

#define WHEEL_PER_SIDE 2 // front, rear

namespace ConsoleColor 
{
    inline constexpr const char* RESET = "\033[0m";
    inline constexpr const char* BLUE  = "\033[34m"; // Info
    inline constexpr const char* YELLOW= "\033[33m"; // Warn
    inline constexpr const char* RED   = "\033[31m"; // Error
}

#define LOGI(node, fmt, ...) RCLCPP_INFO((node)->get_logger(),  (std::string(ConsoleColor::BLUE)   + fmt + ConsoleColor::RESET).c_str(), ##__VA_ARGS__)
#define LOGW(node, fmt, ...) RCLCPP_WARN((node)->get_logger(),  (std::string(ConsoleColor::YELLOW) + fmt + ConsoleColor::RESET).c_str(), ##__VA_ARGS__)
#define LOGWO(node, fmt, ...) RCLCPP_WARN_ONCE((node)->get_logger(),  (std::string(ConsoleColor::YELLOW) + fmt + ConsoleColor::RESET).c_str(), ##__VA_ARGS__)
#define LOGE(node, fmt, ...) RCLCPP_ERROR((node)->get_logger(), (std::string(ConsoleColor::RED)    + fmt + ConsoleColor::RESET).c_str(), ##__VA_ARGS__)

using CallbackReturn = rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn;
using test_husky_controller::ParamListener;
using test_husky_controller::Params;

namespace fr3_husky_controller
{
class TestHuskyController : public controller_interface::ControllerInterface
{
    using Twist = geometry_msgs::msg::TwistStamped;

    public:
        // ========================================================================
        // ============================ Core Functions ============================
        // ========================================================================
        [[nodiscard]] controller_interface::InterfaceConfiguration state_interface_configuration() const override;
        [[nodiscard]] controller_interface::InterfaceConfiguration command_interface_configuration() const override;
        CallbackReturn on_init() override;
        CallbackReturn on_configure(const rclcpp_lifecycle::State & previous_state) override;
        CallbackReturn on_activate(const rclcpp_lifecycle::State & previous_state) override;
        CallbackReturn on_deactivate(const rclcpp_lifecycle::State & previous_state) override;
        CallbackReturn on_cleanup(const rclcpp_lifecycle::State & previous_state) override;
        CallbackReturn on_error(const rclcpp_lifecycle::State & previous_state) override;
        controller_interface::return_type update(const rclcpp::Time & time, const rclcpp::Duration & period) override;

    private:
        // ========================================================================
        // ====================== Main Controller Functions =======================
        // ========================================================================
        void writeCommandInterfaces(const Eigen::VectorXd& command_velocity);
        bool updateJointStates();			
        void updateRobotData();
        void setInitfromCurrent();

        // ========================================================================
        // ============================ Husky robot Data ==========================
        // ========================================================================
        std::shared_ptr<drc::Mobile::RobotData> robot_data_;
        std::shared_ptr<drc::Mobile::RobotController> robot_controller_;

        //// Mobile Base pose wrt world frame
        Eigen::Affine2d base_pose_w_;
        Eigen::Affine2d base_pose_desired_w_;
        Eigen::Affine2d base_pose_init_w_;
        
        //// Mobile Base velocity wrt world frame
        Eigen::Vector3d base_vel_w_;
        Eigen::Vector3d base_vel_desired_w_;
        Eigen::Vector3d base_vel_init_w_;

        //// Mobile Base velocity wrt base frame
        Eigen::Vector3d base_vel_b_;
        Eigen::Vector3d base_vel_desired_b_;
        Eigen::Vector3d base_vel_init_b_;

        Eigen::Vector2d wheel_pos_; // (left, right)
        Eigen::Vector2d wheel_vel_; // (left, right)

        //// control input
        Eigen::Vector2d wheel_vel_desired_; // (left, right)

        // ========================================================================
        // =========================== Controller data ============================
        // ========================================================================
        double play_time_ = 0.0;
        double control_start_time_ = 0.0;
        double dt_ = 0.0;

    protected:

        


        struct WheelHandle
        {
            std::vector<std::reference_wrapper<const hardware_interface::LoanedStateInterface>> feedback; // position, velocity
            std::reference_wrapper<hardware_interface::LoanedCommandInterface> input;
        };


        std::vector<WheelHandle> registered_left_wheel_handles_;
        std::vector<WheelHandle> registered_right_wheel_handles_;

        // Parameters from ROS for diff_drive_controller
        std::shared_ptr<ParamListener> param_listener_;
        Params params_;

        // Odometry odometry_;

        // Timeout to consider cmd_vel commands old
        std::chrono::milliseconds cmd_vel_timeout_{500};

        std::shared_ptr<rclcpp::Publisher<nav_msgs::msg::Odometry>> odometry_publisher_ = nullptr;
        std::shared_ptr<realtime_tools::RealtimePublisher<nav_msgs::msg::Odometry>>
            realtime_odometry_publisher_ = nullptr;

        std::shared_ptr<rclcpp::Publisher<tf2_msgs::msg::TFMessage>> odometry_transform_publisher_ =
            nullptr;
        std::shared_ptr<realtime_tools::RealtimePublisher<tf2_msgs::msg::TFMessage>>
            realtime_odometry_transform_publisher_ = nullptr;

        bool subscriber_is_active_ = false;
        rclcpp::Subscription<Twist>::SharedPtr velocity_command_subscriber_ = nullptr;
        rclcpp::Subscription<geometry_msgs::msg::Twist>::SharedPtr
            velocity_command_unstamped_subscriber_ = nullptr;

        realtime_tools::RealtimeBox<std::shared_ptr<Twist>> received_velocity_msg_ptr_{nullptr};


        // speed limiters
        // SpeedLimiter limiter_linear_;
        // SpeedLimiter limiter_angular_;


        // publish rate limiter
        double publish_rate_ = 50.0;
        rclcpp::Duration publish_period_ = rclcpp::Duration::from_nanoseconds(0);
        rclcpp::Time previous_publish_timestamp_{0, 0, RCL_CLOCK_UNINITIALIZED};

        bool is_halted = false;
        bool use_stamped_vel_ = true;

        bool reset();
};
}  // namespace fr3_husky_controller
