#pragma once

#include <string>
#include <chrono>
#include <array>
#include <memory>
#include <mutex>
#include <cassert>
#include <cmath>
#include <exception>
#include <map>
#include <functional>
#include <vector>
#include <algorithm>
#include <numeric>
#include <sstream>
#include <type_traits>
#include <Eigen/Eigen>

#if __cplusplus < 201703L
// Fallback for toolchains/IntelliSense not using C++17.
namespace std {
template <class From, class To>
constexpr bool is_convertible_v = std::is_convertible<From, To>::value;
}  // namespace std
#endif

#include <rclcpp/rclcpp.hpp>
#include <ament_index_cpp/get_package_share_directory.hpp>
#include <controller_interface/controller_interface.hpp>
#include <controller_interface/helpers.hpp>
#include <hardware_interface/loaned_command_interface.hpp>
#include <hardware_interface/types/hardware_interface_type_values.hpp>
#include <rclcpp_action/create_server.hpp>
#include <rclcpp_action/server_goal_handle.hpp>
#include <rclcpp_lifecycle/state.hpp>
#include <geometry_msgs/msg/pose_stamped.hpp>

#include <franka_semantic_components/franka_robot_model.hpp>
#include <franka_semantic_components/franka_robot_state.hpp>
#include <franka/lowpass_filter.h>

// auto-generated by generate_parameter_library
#include "fr3_husky_controller/test_fr3_controller_parameters.hpp"

#include <fr3_husky_controller/utils/dyros_math.h>
#include <fr3_husky_controller/utils/robot_utils.hpp>

#include "dyros_robot_controller/manipulator/robot_data.h"
#include "dyros_robot_controller/manipulator/robot_controller.h"

#define FR3_DOF 7

namespace ConsoleColor 
{
    inline constexpr const char* RESET = "\033[0m";
    inline constexpr const char* BLUE  = "\033[34m"; // Info
    inline constexpr const char* YELLOW= "\033[33m"; // Warn
    inline constexpr const char* RED   = "\033[31m"; // Error
}

#define LOGI(node, fmt, ...) RCLCPP_INFO((node)->get_logger(),  (std::string(ConsoleColor::BLUE)   + fmt + ConsoleColor::RESET).c_str(), ##__VA_ARGS__)
#define LOGW(node, fmt, ...) RCLCPP_WARN((node)->get_logger(),  (std::string(ConsoleColor::YELLOW) + fmt + ConsoleColor::RESET).c_str(), ##__VA_ARGS__)
#define LOGE(node, fmt, ...) RCLCPP_ERROR((node)->get_logger(), (std::string(ConsoleColor::RED)    + fmt + ConsoleColor::RESET).c_str(), ##__VA_ARGS__)

using CallbackReturn = rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn;
using test_fr3_controller::ParamListener;
using test_fr3_controller::Params;

namespace fr3_husky_controller 
{
class TestFR3Controller : public controller_interface::ControllerInterface 
{
    public:
        // ========================================================================
        // ============================ Core Functions ============================
        // ========================================================================
        [[nodiscard]] controller_interface::InterfaceConfiguration state_interface_configuration() const override;
        [[nodiscard]] controller_interface::InterfaceConfiguration command_interface_configuration() const override;
        CallbackReturn on_init() override;
        CallbackReturn on_configure(const rclcpp_lifecycle::State& previous_state) override;
        CallbackReturn on_activate(const rclcpp_lifecycle::State& previous_state) override;
        CallbackReturn on_deactivate(const rclcpp_lifecycle::State& previous_state) override;
        controller_interface::return_type update(const rclcpp::Time& time, const rclcpp::Duration& period) override;

    private:
        // ========================================================================
        // ====================== Main Controller Functions =======================
        // ========================================================================
        void writeCommandInterfaces(const Eigen::VectorXd& command_position,
                                    const Eigen::VectorXd& command_velocity,
                                    const Eigen::VectorXd& command_effort);
        void updateJointStates();			
        void updateRobotData();
        
        bool loadDRCGains();
        void setInitfromCurrent();
        // ========================================================================
        // =========================== Franka robot Data ==========================
        // ========================================================================
        std::vector<std::unique_ptr<franka_semantic_components::FrankaRobotModel>> franka_robot_model_;
        std::shared_ptr<drc::Manipulator::RobotData> robot_data_;
        std::unique_ptr<drc::Manipulator::RobotController> robot_controller_;

        // ====== Joint space data ======
        // initial state
        std::vector<Eigen::Vector7d> q_init_;
        std::vector<Eigen::Vector7d> qdot_init_;
        std::vector<Eigen::Vector7d> qddot_init_;
        Eigen::VectorXd q_total_init_;
        Eigen::VectorXd qdot_total_init_;
        Eigen::VectorXd qddot_total_init_;

        bool hold_init_valid_{false};

        // current state
        std::vector<Eigen::Vector7d> q_;
        std::vector<Eigen::Vector7d> qdot_;
        std::vector<Eigen::Vector7d> qddot_;
        std::vector<Eigen::Vector7d> torque_;
        Eigen::VectorXd q_total_;
        Eigen::VectorXd qdot_total_;
        Eigen::VectorXd qddot_total_;
        Eigen::VectorXd torque_total_;

        // desired state
        std::vector<Eigen::Vector7d> q_desired_;
        std::vector<Eigen::Vector7d> qdot_desired_;
        std::vector<Eigen::Vector7d> torque_desired_;
        Eigen::VectorXd q_desired_total_;
        Eigen::VectorXd qdot_desired_total_;
        Eigen::VectorXd torque_desired_total_;

        // Dynamics
        std::vector<Eigen::Matrix7d> M_;
        std::vector<Eigen::Matrix7d> M_inv_;
        std::vector<Eigen::Vector7d> c_;
        std::vector<Eigen::Vector7d> g_;
        Eigen::MatrixXd M_total_;
        Eigen::MatrixXd M_inv_total_;
        Eigen::VectorXd c_total_;
        Eigen::VectorXd g_total_;

        // ====== Task space data =======
        std::vector<std::string> ee_name_;

        // initial state
        std::vector<Eigen::Affine3d> x_init_;
        std::vector<Eigen::Vector6d> xdot_init_;

        // current state
        std::vector<Eigen::Affine3d> x_;
        std::vector<Eigen::Vector6d> xdot_;
        std::vector<Eigen::Matrix<double, 6, FR3_DOF>> J_;

        // desierd state
        std::vector<Eigen::Affine3d> x_desired_;
        std::vector<Eigen::Vector6d> xdot_desired_;


        // ========================================================================
        // =========================== Controller data ============================
        // ========================================================================
        size_t num_robots_;
        double dt_{0.0};
        double play_time_{0.0};
        double control_start_time_{0.0};

        const std::string arm_id_{"fr3"};

        // ========================================================================
        // ============================== Parameters ==============================
        // ========================================================================
        std::shared_ptr<ParamListener> param_listener_;
        Params params_;
        size_t dof_{0};
        bool initialization_flag_{true};

        // dyros_robot_controller gains
        Eigen::VectorXd joint_kp_;
        Eigen::VectorXd joint_kv_;
        Eigen::VectorXd qpik_damping_;
        Eigen::VectorXd qpid_vel_damping_;
        Eigen::VectorXd qpid_acc_damping_;
        std::map<std::string, Eigen::Vector6d> link_task_kp_;
        std::map<std::string, Eigen::Vector6d> link_task_kv_;
        std::map<std::string, Eigen::Vector6d> link_qpik_tracking_;
        std::map<std::string, Eigen::Vector6d> link_qpid_tracking_;

        // ========================================================================
        // ============================ Mutex & Thread ============================
        // ========================================================================
        std::mutex robot_data_mutex_;

        // To reduce number of variables and to make the code shorter the interfaces are ordered in types
        // as the following constants
        const std::vector<std::string> allowed_interface_types_ = {
            hardware_interface::HW_IF_POSITION,
            hardware_interface::HW_IF_VELOCITY,
            hardware_interface::HW_IF_ACCELERATION,
            hardware_interface::HW_IF_EFFORT,
        };
        
        // The interfaces are defined as the types in 'allowed_interface_types_' member.
        // For convenience, for each type the interfaces are ordered so that i-th position
        // matches i-th index in joint_names_
        template <typename T>
        using InterfaceReferences = std::vector<std::vector<std::reference_wrapper<T>>>;

        InterfaceReferences<hardware_interface::LoanedCommandInterface> joint_command_interface_; //[interface_type_idx][joint_idx]
        InterfaceReferences<hardware_interface::LoanedStateInterface> joint_state_interface_; //[interface_type_idx][joint_idx]

        bool has_position_state_interface_ = false;
        bool has_velocity_state_interface_ = false;
        bool has_effort_state_interface_ = false;
        bool has_position_command_interface_ = false;
        bool has_velocity_command_interface_ = false;
        bool has_effort_command_interface_ = false;
};

}  // namespace fr3_husky_controller
