#pragma once

#include <string>
#include <chrono>
#include <thread>
#include <condition_variable>
#include <atomic>
#include <array>
#include <memory>
#include <mutex>
#include <cassert>
#include <cmath>
#include <exception>
#include <future>
#include <map>
#include <functional>
#include <vector>

#include <Eigen/Eigen>

#include <rclcpp/rclcpp.hpp>
#include <ament_index_cpp/get_package_share_directory.hpp>
#include <controller_interface/controller_interface.hpp>
#include <controller_interface/helpers.hpp>
#include "hardware_interface/loaned_command_interface.hpp"
#include "hardware_interface/types/hardware_interface_type_values.hpp"


// auto-generated by generate_parameter_library
#include "fr3_husky_controller/test_single_fr3_controller_parameters.hpp"

#include "franka_semantic_components/franka_robot_model.hpp"
#include "franka_semantic_components/franka_robot_state.hpp"

#include "fr3_husky_controller/utils/dyros_math.h"
#include "fr3_husky_controller/utils/benchmark.h"

#include "rclcpp_action/create_server.hpp"
#include "rclcpp_action/server_goal_handle.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "geometry_msgs/msg/pose_stamped.hpp"

#include "fr3_husky_controller/action/move_link.hpp"

#include "rclcpp/version.h"
#if RCLCPP_VERSION_GTE(29, 0, 0)
#include "urdf/model.hpp"
#else
#include "urdf/model.h"
#endif

#include "dyros_robot_controller/manipulator/robot_data.h"
#include "dyros_robot_controller/manipulator/robot_controller.h"


namespace ConsoleColor 
{
    inline constexpr const char* RESET = "\033[0m";
    inline constexpr const char* BLUE  = "\033[34m"; // Info
    inline constexpr const char* YELLOW= "\033[33m"; // Warn
    inline constexpr const char* RED   = "\033[31m"; // Error
}

#define LOGI(node, fmt, ...) RCLCPP_INFO((node)->get_logger(),  (std::string(ConsoleColor::BLUE)   + fmt + ConsoleColor::RESET).c_str(), ##__VA_ARGS__)
#define LOGW(node, fmt, ...) RCLCPP_WARN((node)->get_logger(),  (std::string(ConsoleColor::YELLOW) + fmt + ConsoleColor::RESET).c_str(), ##__VA_ARGS__)
#define LOGE(node, fmt, ...) RCLCPP_ERROR((node)->get_logger(), (std::string(ConsoleColor::RED)    + fmt + ConsoleColor::RESET).c_str(), ##__VA_ARGS__)

using CallbackReturn = rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn;
using joint_trajectory_controller::ParamListener;
using joint_trajectory_controller::Params;

namespace FR3HuskyController 
{
class TestSingleFR3Controller : public controller_interface::ControllerInterface 
{
    public:
        // ========================================================================
        // ============================ Core Functions ============================
        // ========================================================================
        [[nodiscard]] controller_interface::InterfaceConfiguration command_interface_configuration() const override;
        [[nodiscard]] controller_interface::InterfaceConfiguration state_interface_configuration() const override;
        CallbackReturn on_init() override;
        CallbackReturn on_configure(const rclcpp_lifecycle::State& previous_state) override;
        CallbackReturn on_activate(const rclcpp_lifecycle::State& previous_state) override;
        CallbackReturn on_deactivate(const rclcpp_lifecycle::State& previous_state) override;
        controller_interface::return_type update(const rclcpp::Time& time, const rclcpp::Duration& period) override;

    private:
        using MoveLink = fr3_husky_controller::action::MoveLink;
        using GoalHandleMoveLink = rclcpp_action::ServerGoalHandle<MoveLink>;

        // ========================================================================
        // ====================== Main Controller Functions =======================
        // ========================================================================
        void compute();
        void updateJointStates();			
        void updateRobotData();
        void computeWorkerLoop();
        bool loadDyrosGains();
        bool ensureLinkGains(const std::string& link_name);

        // ========================================================================
        // =========================== Franka robot Data ==========================
        // ========================================================================
        std::unique_ptr<franka_semantic_components::FrankaRobotModel> franka_robot_model_;
        std::shared_ptr<drc::Manipulator::RobotData> robot_data_;
        std::unique_ptr<drc::Manipulator::RobotController> robot_controller_;

        // ====== Joint space data ======
        // initial state
        Eigen::Vector7d q_init_;
        Eigen::Vector7d qdot_init_;
        Eigen::Vector7d qddot_init_;

        // current state
        Eigen::Vector7d q_;
        Eigen::Vector7d qdot_;
        Eigen::Vector7d qddot_;
        Eigen::Vector7d torque_;

        // desired state
        Eigen::Vector7d q_desired_;
        Eigen::Vector7d qdot_desired_;
        Eigen::Vector7d torque_desired_;

        // Dynamics
        Eigen::Matrix7d M_;
        Eigen::Matrix7d M_inv_;
        Eigen::Vector7d c_;
        Eigen::Vector7d g_;

        // ====== Task space data =======
        // initial state
        Eigen::Affine3d x_init_;
        Eigen::Vector6d xdot_init_;

        // current state
        Eigen::Affine3d x_;
        Eigen::Vector6d xdot_;
        Eigen::Matrix<double, 6, 7> J_;

        // desierd state
        Eigen::Affine3d x_desired_;
        Eigen::Vector6d xdot_desired_;

        // Dynamics
        Eigen::Matrix6d M_task_;
        Eigen::Vector6d g_task_;
        Eigen::Matrix<double, 6, 7> J_T_inv_;

        // ========================================================================
        // =========================== Controller data ============================
        // ========================================================================
        double dt_{0.0};
        double play_time_{0.0};
        double control_start_time_{0.0};

        Benchmark bench_timer_;

        std::string arm_id_{"fr3"};

        // ========================================================================
        // ============================== Parameters ==============================
        // ========================================================================
        std::shared_ptr<ParamListener> param_listener_;
        Params params_;
        size_t dof_{0};
        bool initialization_flag_{true};
        std::vector<bool> joints_angle_wraparound_;

        // ========================================================================
        // ============================ Mutex & Thread ============================
        // ========================================================================
        std::mutex robot_data_mutex_;
        std::mutex calculation_mutex_;
        std::atomic<bool> compute_inflight_{false};
        std::atomic<bool> relax_wait_guard_{false};
        std::thread compute_thread_;
        std::mutex compute_cv_mutex_;
        std::condition_variable compute_cv_;
        std::condition_variable compute_done_cv_;
        bool compute_requested_{false};
        bool compute_completed_{false};
        bool stop_compute_thread_{false};



        // Storing command joint names for interfaces
        std::vector<std::string> command_joint_names_;
        size_t num_cmd_joints_{0};
        std::vector<size_t> map_cmd_to_joints_;

        // To reduce number of variables and to make the code shorter the interfaces are ordered in types
        // as the following constants
        const std::vector<std::string> allowed_interface_types_ = {
            hardware_interface::HW_IF_POSITION,
            hardware_interface::HW_IF_VELOCITY,
            hardware_interface::HW_IF_ACCELERATION,
            hardware_interface::HW_IF_EFFORT,
        };
        
        // The interfaces are defined as the types in 'allowed_interface_types_' member.
        // For convenience, for each type the interfaces are ordered so that i-th position
        // matches i-th index in joint_names_
        template <typename T>
        using InterfaceReferences = std::vector<std::vector<std::reference_wrapper<T>>>;

        InterfaceReferences<hardware_interface::LoanedCommandInterface> joint_command_interface_; //[interface_type_idx][joint_idx]
        InterfaceReferences<hardware_interface::LoanedStateInterface> joint_state_interface_; //[interface_type_idx][joint_idx]

        bool has_position_state_interface_ = false;
        bool has_velocity_state_interface_ = false;
        bool has_acceleration_state_interface_ = false;
        bool has_effort_state_interface_ = false;
        bool has_position_command_interface_ = false;
        bool has_velocity_command_interface_ = false;
        bool has_effort_command_interface_ = false;

        rclcpp_action::Server<MoveLink>::SharedPtr action_server_;
        rclcpp::Duration action_monitor_period_{0, 0};
        std::shared_ptr<GoalHandleMoveLink> active_goal_handle_;
        std::string active_link_name_;
        double action_duration_{0.0};
        double last_action_feedback_time_{0.0};
        bool action_active_{false};
        std::map<std::string, drc::TaskSpaceData> link_task_data_;
        std::string default_task_link_{"fr3_link8"};

        Eigen::VectorXd joint_kp_;
        Eigen::VectorXd joint_kv_;
        Eigen::VectorXd qpik_damping_;
        Eigen::VectorXd qpid_vel_damping_;
        Eigen::VectorXd qpid_acc_damping_;
        Eigen::Vector6d default_task_kp_;
        Eigen::Vector6d default_task_kv_;
        Eigen::Vector6d default_qpik_tracking_;
        Eigen::Vector6d default_qpid_tracking_;
        std::map<std::string, Eigen::Vector6d> link_task_kp_;
        std::map<std::string, Eigen::Vector6d> link_task_kv_;
        std::map<std::string, Eigen::Vector6d> link_qpik_tracking_;
        std::map<std::string, Eigen::Vector6d> link_qpid_tracking_;

        // callbacks for action_server_
        rclcpp_action::GoalResponse goal_received_callback(const rclcpp_action::GoalUUID & uuid, std::shared_ptr<const MoveLink::Goal> goal);
        rclcpp_action::CancelResponse goal_cancelled_callback(const std::shared_ptr<GoalHandleMoveLink> goal_handle);
        void goal_accepted_callback(std::shared_ptr<GoalHandleMoveLink> goal_handle);
};

}  // namespace FR3HuskyController
