#pragma once

#include <string>
#include <chrono>
#include <array>
#include <memory>
#include <mutex>
#include <cassert>
#include <cmath>
#include <exception>
#include <map>
#include <functional>
#include <vector>
#include <algorithm>
#include <numeric>
#include <sstream>
#include <type_traits>
#include <Eigen/Eigen>

#if __cplusplus < 201703L
// Fallback for toolchains/IntelliSense not using C++17.
namespace std {
template <class From, class To>
constexpr bool is_convertible_v = std::is_convertible<From, To>::value;
}  // namespace std
#endif

#include <rclcpp/rclcpp.hpp>
#include <ament_index_cpp/get_package_share_directory.hpp>
#include <controller_interface/controller_interface.hpp>
#include <controller_interface/helpers.hpp>
#include <hardware_interface/loaned_command_interface.hpp>
#include <hardware_interface/types/hardware_interface_type_values.hpp>
#include <rclcpp_action/create_server.hpp>
#include <rclcpp_action/server_goal_handle.hpp>
#include <rclcpp_lifecycle/state.hpp>
#include <geometry_msgs/msg/pose_stamped.hpp>
#include "lifecycle_msgs/msg/state.hpp"

#include <franka_semantic_components/franka_robot_model.hpp>
#include <franka_semantic_components/franka_robot_state.hpp>
#include <franka/lowpass_filter.h>

// auto-generated by generate_parameter_library
#include "fr3_husky_controller/test_fr3_controller_parameters.hpp"

#include <fr3_husky_controller/utils/dyros_math.h>
#include <fr3_husky_controller/utils/robot_utils.hpp>

#include "dyros_robot_controller/manipulator/robot_data.h"
#include "dyros_robot_controller/manipulator/robot_controller.h"

#define FR3_DOF 7

namespace ConsoleColor 
{
    inline constexpr const char* RESET = "\033[0m";
    inline constexpr const char* BLUE  = "\033[34m"; // Info
    inline constexpr const char* YELLOW= "\033[33m"; // Warn
    inline constexpr const char* RED   = "\033[31m"; // Error
}

#define LOGI(node, fmt, ...) RCLCPP_INFO((node)->get_logger(),  (std::string(ConsoleColor::BLUE)   + fmt + ConsoleColor::RESET).c_str(), ##__VA_ARGS__)
#define LOGW(node, fmt, ...) RCLCPP_WARN((node)->get_logger(),  (std::string(ConsoleColor::YELLOW) + fmt + ConsoleColor::RESET).c_str(), ##__VA_ARGS__)
#define LOGE(node, fmt, ...) RCLCPP_ERROR((node)->get_logger(), (std::string(ConsoleColor::RED)    + fmt + ConsoleColor::RESET).c_str(), ##__VA_ARGS__)

using CallbackReturn = rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn;
using test_fr3_controller::ParamListener;
using test_fr3_controller::Params;

namespace fr3_husky_controller 
{
class TestFR3Controller : public controller_interface::ControllerInterface 
{
    // Shared interface slot indices
    inline static constexpr size_t kPositionIndex = 0;
    inline static constexpr size_t kVelocityIndex = 1;
    inline static constexpr size_t kEffortIndex   = 2;
    inline static constexpr size_t kFeedbackPositionIndex = 0;
    inline static constexpr size_t kFeedbackVelocityIndex = 1;
    inline static constexpr size_t kFeedbackEffortIndex = 2;

    public:
        // ========================================================================
        // ============================ Core Functions ============================
        // ========================================================================
        [[nodiscard]] controller_interface::InterfaceConfiguration state_interface_configuration() const override;
        [[nodiscard]] controller_interface::InterfaceConfiguration command_interface_configuration() const override;
        CallbackReturn on_init() override;
        CallbackReturn on_configure(const rclcpp_lifecycle::State& previous_state) override;
        CallbackReturn on_activate(const rclcpp_lifecycle::State& previous_state) override;
        CallbackReturn on_deactivate(const rclcpp_lifecycle::State& previous_state) override;
        controller_interface::return_type update(const rclcpp::Time& time, const rclcpp::Duration& period) override;

    private:
        // ========================================================================
        // ====================== Main Controller Functions =======================
        // ========================================================================
        void writeCommandInterfaces(const Eigen::VectorXd& command);
        void updateJointStates();			
        void updateRobotData();
        
        bool loadDRCGains();
        void setInitfromCurrent();

        // ========================================================================
        // =========================== Franka robot Data ==========================
        // ========================================================================
        std::vector<std::unique_ptr<franka_semantic_components::FrankaRobotModel>> franka_robot_model_;
        std::shared_ptr<drc::Manipulator::RobotData> robot_data_;
        std::unique_ptr<drc::Manipulator::RobotController> robot_controller_;

        // ========================================================================
        // ======================= Manipulator State Data =========================
        // ========================================================================
        struct ManipulatorState
        {
            // Initial
            std::vector<Eigen::Vector<double, FR3_DOF>> q_init;
            std::vector<Eigen::Vector<double, FR3_DOF>> qdot_init;
            std::vector<Eigen::Vector<double, FR3_DOF>> qddot_init;
            Eigen::VectorXd q_total_init;
            Eigen::VectorXd qdot_total_init;
            Eigen::VectorXd qddot_total_init;
    
            // Current
            std::vector<Eigen::Vector<double, FR3_DOF>> q;
            std::vector<Eigen::Vector<double, FR3_DOF>> qdot;
            std::vector<Eigen::Vector<double, FR3_DOF>> qddot;
            std::vector<Eigen::Vector<double, FR3_DOF>> torque;
            Eigen::VectorXd q_total;
            Eigen::VectorXd qdot_total;
            Eigen::VectorXd qddot_total;
            Eigen::VectorXd torque_total;
    
            // Desired
            std::vector<Eigen::Vector<double, FR3_DOF>> q_desired;
            std::vector<Eigen::Vector<double, FR3_DOF>> qdot_desired;
            std::vector<Eigen::Vector<double, FR3_DOF>> torque_desired;
            Eigen::VectorXd q_desired_total;
            Eigen::VectorXd qdot_desired_total;
            Eigen::VectorXd torque_desired_total;
    
            // Dynamics
            std::vector<Eigen::Matrix<double, FR3_DOF, FR3_DOF>> M;
            std::vector<Eigen::Matrix<double, FR3_DOF, FR3_DOF>> M_inv;
            std::vector<Eigen::Vector<double, FR3_DOF>> c;
            std::vector<Eigen::Vector<double, FR3_DOF>> g;
            Eigen::MatrixXd M_total;
            Eigen::MatrixXd M_inv_total;
            Eigen::VectorXd c_total;
            Eigen::VectorXd g_total;
        };

        ManipulatorState mani_state_;

        // ========================================================================
        // ============================= Task Space Data ==========================
        // ========================================================================
        std::vector<std::string> ee_name_;
        std::map<std::string, drc::TaskSpaceData> ee_data_;

        // ========================================================================
        // =========================== Controller data ============================
        // ========================================================================
        size_t num_robots_{0}; // number of FR3 arms
        double dt_{0.0};
        double play_time_{0.0};
        double control_start_time_{0.0};

        const std::string arm_id_{"fr3"};

        // ========================================================================
        // ============================== Parameters ==============================
        // ========================================================================
        std::shared_ptr<ParamListener> param_listener_;
        Params params_;

        size_t manipulator_dof_{0};

        // dyros_robot_controller gains
        Eigen::VectorXd mani_joint_kp_;
        Eigen::VectorXd mani_joint_kv_;
        Eigen::VectorXd qpik_mani_damping_;
        Eigen::VectorXd qpid_mani_vel_damping_;
        Eigen::VectorXd qpid_mani_acc_damping_;
        std::map<std::string, Eigen::Vector6d> task_kp_;
        std::map<std::string, Eigen::Vector6d> task_kv_;
        std::map<std::string, Eigen::Vector6d> qpik_tracking_;
        std::map<std::string, Eigen::Vector6d> qpid_tracking_;

        // ========================================================================
        // ============================ Mutex & Thread ============================
        // ========================================================================
        std::mutex robot_data_mutex_;

        // ========================================================================
        // ============================ Interfaces Setup ==========================
        // ========================================================================
        // Interface ordering (keeps indices consistent across interface types).
        const std::vector<std::string> allowed_interface_types_ = {
            hardware_interface::HW_IF_POSITION,
            hardware_interface::HW_IF_VELOCITY,
            hardware_interface::HW_IF_EFFORT,
        };
        
        struct JointHandle
        {
            std::vector<std::reference_wrapper<hardware_interface::LoanedStateInterface>> state;
            std::reference_wrapper<hardware_interface::LoanedCommandInterface> command;

            explicit JointHandle(std::reference_wrapper<hardware_interface::LoanedCommandInterface> cmd)
            : command(cmd) {}
        };

        // Manipulator joint handles 
        mutable std::vector<JointHandle> registered_manipulator_joint_handles_;

        bool has_position_state_interface_ = false;
        bool has_velocity_state_interface_ = false;
        bool has_effort_state_interface_ = false;
        bool has_position_command_interface_ = false;
        bool has_velocity_command_interface_ = false;
        bool has_effort_command_interface_ = false;

        bool is_halted_ = false;
};

}  // namespace fr3_husky_controller
