# Define the goal
bool enable  # true: enable gravity-comp mode (take ownership), false: disable (release)

---
# Define the result
bool is_completed
---
# Define a feedback message
bool is_qp_solved
string time_verbose